### ISSUE TITLE
Protonvpn: port forwarding connection timeout

### ISSUE THREAD

**Issue by sruffilli** [passteque/gluetun#1757]
### Is this urgent?

None

### Host OS

Ubuntu 22.10

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-07-18T15:57:47.027Z (commit abe2ace)

### What's the problem 🤔

It looks like querying to get the port-forwarding port always fail for me with a timeout error.
I tried multiple P2P cities to no avail.

### Share your logs

```plain text
gluetun-protonvpn  | 2023-07-21T14:32:23Z INFO [openvpn] [node-ch-06.protonvpn.net] Peer Connection Initiated with [AF_INET]185.159.157.129:443
gluetun-protonvpn  | 2023-07-21T14:32:23Z INFO [openvpn] setsockopt TCP_NODELAY=1 failed
gluetun-protonvpn  | 2023-07-21T14:32:23Z INFO [openvpn] TUN/TAP device tun0 opened
gluetun-protonvpn  | 2023-07-21T14:32:23Z INFO [openvpn] /sbin/ip link set dev tun0 up mtu 1500
gluetun-protonvpn  | 2023-07-21T14:32:24Z INFO [openvpn] /sbin/ip link set dev tun0 up
gluetun-protonvpn  | 2023-07-21T14:32:24Z INFO [openvpn] /sbin/ip addr add dev tun0 10.31.0.11/16
gluetun-protonvpn  | 2023-07-21T14:32:24Z INFO [openvpn] UID set to nonrootuser
gluetun-protonvpn  | 2023-07-21T14:32:24Z INFO [openvpn] Initialization Sequence Completed
gluetun-protonvpn  | 2023-07-21T14:32:24Z INFO [dns over tls] downloading DNS over TLS cryptographic files
gluetun-protonvpn  | 2023-07-21T14:32:24Z INFO [healthcheck] healthy!
gluetun-protonvpn  | 2023-07-21T14:32:25Z INFO [dns over tls] downloading hostnames and IP block lists
gluetun-protonvpn  | 2023-07-21T14:32:32Z INFO [healthcheck] unhealthy: dialing: dial tcp4: lookup cloudflare.com: i/o timeout
gluetun-protonvpn  | 2023-07-21T14:32:33Z INFO [dns over tls] init module 0: validator
gluetun-protonvpn  | 2023-07-21T14:32:33Z INFO [dns over tls] init module 1: iterator
gluetun-protonvpn  | 2023-07-21T14:32:34Z INFO [dns over tls] start of service (unbound 1.17.1).
gluetun-protonvpn  | 2023-07-21T14:32:34Z INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
gluetun-protonvpn  | 2023-07-21T14:32:34Z INFO [dns over tls] generate keytag query _ta-4a5c-4f66. NULL IN
gluetun-protonvpn  | 2023-07-21T14:32:34Z INFO [dns over tls] ready
gluetun-protonvpn  | 2023-07-21T14:32:34Z INFO [healthcheck] healthy!
gluetun-protonvpn  | 2023-07-21T14:32:34Z INFO [vpn] You are running 1 commit behind the most recent latest
gluetun-protonvpn  | 2023-07-21T14:32:34Z INFO [ip getter] Public IP address is 185.159.157.21 (Switzerland, Zurich, Zürich)
gluetun-protonvpn  | 2023-07-21T14:32:34Z INFO [vpn] VPN gateway IP address: 10.31.0.1
gluetun-protonvpn  | 2023-07-21T14:34:42Z ERROR [port forwarding] getting external IPv4 address: executing remote procedure call: connection timeout: after 2m7.75s
gluetun-protonvpn  | 2023-07-21T14:34:42Z INFO [port forwarding] retrying in 5s
gluetun-protonvpn  | 2023-07-21T14:36:55Z ERROR [port forwarding] getting external IPv4 address: executing remote procedure call: connection timeout: after 2m7.75s
gluetun-protonvpn  | 2023-07-21T14:36:55Z INFO [port forwarding] retrying in 5s
gluetun-protonvpn  | 2023-07-21T14:39:08Z ERROR [port forwarding] getting external IPv4 address: executing remote procedure call: connection timeout: after 2m7.75s
gluetun-protonvpn  | 2023-07-21T14:39:08Z INFO [port forwarding] retrying in 5s
```

### Share your configuration

```yml
services:
  gluetun-protonvpn:
    image: qmcgaw/gluetun:latest
    container_name: gluetun-protonvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${CONFIGS_PATH}/gluetun:/tmp/gluetun
    ports:
      - [...]
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn      
      - OPENVPN_USER=<user>+pmp
      - OPENVPN_PASSWORD=<pass>
      - SERVER_COUNTRIES={Switzerland, France, Italy, Spain}
      - FIREWALL_OUTBOUND_SUBNETS=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - VPN_ENDPOINT_PORT=443
      - VPN_PORT_FORWARDING=on
      - TZ=Etc/UTC
    restart: always
```
